- name: Build Docker Image
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Building Docker Image
      docker_image:
         name: 66022444:latest
         source: build
         build:
            path: ~/66022444  # แหล่งที่อยู่ของ source code บน Docker server
         state: present
         force_source: true

