- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Creating the Container
      docker_container:
         name: 66022444HTML-container
         image: 66022444HTML:latest
         ports:
           - "3022:80"  # พอร์ต 3022 บนเครื่อง Docker server -> 80 บน Docker container
         state: started
         restart: true
